### ISSUE TITLE
Wrong repository in readme

### ISSUE THREAD

**Issue by arjanhulst** [channelengine/api-client-php#1]
I tried installing the client with composer, following the readme. The repository url mentioned in the readme misses the -php part. It should be https://github.com/channelengine/api-client-php.git instead of https://github.com/channelengine/api-client.git?

**Comment by smitj** [comment]
The installation process as described in the readme is indeed faulty. It's not the only thing that needs to be fixed.

Instead of manually adding a specific repository for this library, it is also available on [packagist](https://packagist.org/packages/channelengine/api-client). Running`composer require channelengine/api-client:dev-master` should install the package for you.

**Comment by christiaanderidder** [comment]
The composer spec and readme have been fixed to match the repository name. This does mean, however that the package name on packagist has also been renamed to `api-client-php`:
https://packagist.org/packages/channelengine/api-client-php
